/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lesson.gradle;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

	private void assertTrue(boolean someLibraryMethod, String string) {
		// TODO Auto-generated method stub
		
	}
}
